### ISSUE TITLE
Warnings still showing in vscode and Rider

### ISSUE THREAD

**Issue by rutgersc** [shuebner/OneOfDiagnosticSuppressor#1]
First of all, thanks for creating this. Such a good idea to enable safe usage of switch, while also being much better explainable to colleagues.

One thing I noticed is that the exhaustiveness warnings still seem to show in some editors like vscode and Rider. Building the project or viewing the file with Visual Studio 2022 suppresses the warnings as expected.

It seems like it's just broken for both of them:
- Rider: [Roslyn: DiagnosticSuppressor Not Working in Rider 2020.2.1](https://youtrack.jetbrains.com/issue/RSRP-481121)
- vscode: [OmniSharp/omnisharp-roslyn#1711](https://github.com/OmniSharp/omnisharp-roslyn/issues/1711)

Just thought I would note it here, as it may spare someone that extra effort to google this issue. Feel free to close this if you think it doesn't belong here! :)

**Comment by shuebner** [comment]
Thank you for the kind words.
And thank you for bringing this up.

I am guilty of considering the dotnet CLI build first, then the Visual Studio development experience ... and nothing else ;-)

As far as I understood your linked issues, there is nothing I can do to fix this.
But I can at least warn people in the README.

Btw, Visual Studio does not by default run diagnostic suppressors when the build is triggered by running a test.
If you have your exhaustiveness diagnostics severity set to error, this will prevent the test from running (unless you do a proper build first).
But at least here you can configure VS to always run analyzers.
I will add that to the README as well.

As soon as I do, I will close this issue.

**Comment by shuebner** [comment]
added to README
